# Dependabot configuration for automated dependency updates
version: 2
updates:
  # Enable version updates for npm packages (pnpm workspace)
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 10
    assignees:
      - '@davebhardwaj'
    reviewers:
      - '@davebhardwaj'
    commit-message:
      prefix: 'chore(deps)'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'automated'
    ignore:
      # Ignore major version updates for critical packages to avoid breaking changes
      - dependency-name: 'react'
        update-types: ['version-update:semver-major']
      - dependency-name: 'react-dom'
        update-types: ['version-update:semver-major']
      - dependency-name: 'typescript'
        update-types: ['version-update:semver-major']
      - dependency-name: 'node'
        update-types: ['version-update:semver-major']
    groups:
      # Group related dependencies together
      react-ecosystem:
        patterns:
          - 'react*'
          - '@types/react*'
        exclude-patterns:
          - 'react-scripts'
      typescript-ecosystem:
        patterns:
          - 'typescript'
          - '@typescript-eslint/*'
          - '@types/*'
      testing-ecosystem:
        patterns:
          - 'jest*'
          - '@testing-library/*'
          - 'playwright*'
          - '@playwright/*'
      eslint-ecosystem:
        patterns:
          - 'eslint*'
          - '@eslint/*'
      build-tools:
        patterns:
          - 'vite*'
          - '@vitejs/*'
          - 'rollup*'
          - 'webpack*'

  # Frontend package dependencies
  - package-ecosystem: 'npm'
    directory: '/apps/frontend'
    schedule:
      interval: 'weekly'
      day: 'tuesday'
      time: '09:00'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore(frontend/deps)'
    labels:
      - 'dependencies'
      - 'frontend'
      - 'automated'

  # Backend Python dependencies
  - package-ecosystem: 'pip'
    directory: '/apps/backend'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
      time: '09:00'
    open-pull-requests-limit: 5
    assignees:
      - '@davebhardwaj'
    commit-message:
      prefix: 'chore(backend/deps)'
    labels:
      - 'dependencies'
      - 'backend'
      - 'python'
      - 'automated'
    ignore:
      # Ignore major Django updates to avoid breaking changes
      - dependency-name: 'django'
        update-types: ['version-update:semver-major']

  # Shared packages dependencies
  - package-ecosystem: 'npm'
    directory: '/packages/shared'
    schedule:
      interval: 'weekly'
      day: 'thursday'
      time: '09:00'
    open-pull-requests-limit: 3
    commit-message:
      prefix: 'chore(shared/deps)'
    labels:
      - 'dependencies'
      - 'shared'
      - 'automated'

  # UI package dependencies
  - package-ecosystem: 'npm'
    directory: '/packages/ui'
    schedule:
      interval: 'weekly'
      day: 'thursday'
      time: '10:00'
    open-pull-requests-limit: 3
    commit-message:
      prefix: 'chore(ui/deps)'
    labels:
      - 'dependencies'
      - 'ui'
      - 'automated'

  # API package dependencies
  - package-ecosystem: 'npm'
    directory: '/packages/api'
    schedule:
      interval: 'weekly'
      day: 'thursday'
      time: '11:00'
    open-pull-requests-limit: 3
    commit-message:
      prefix: 'chore(api/deps)'
    labels:
      - 'dependencies'
      - 'api'
      - 'automated'

  # Tools dependencies
  - package-ecosystem: 'npm'
    directory: '/tools'
    schedule:
      interval: 'weekly'
      day: 'friday'
      time: '09:00'
    open-pull-requests-limit: 3
    commit-message:
      prefix: 'chore(tools/deps)'
    labels:
      - 'dependencies'
      - 'tools'
      - 'automated'

  # Docker dependencies
  - package-ecosystem: 'docker'
    directory: '/infra/docker'
    schedule:
      interval: 'monthly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 2
    commit-message:
      prefix: 'chore(docker)'
    labels:
      - 'dependencies'
      - 'docker'
      - 'infrastructure'
      - 'automated'

  # GitHub Actions dependencies
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
      day: 'monday'
      time: '10:00'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore(ci)'
    labels:
      - 'dependencies'
      - 'github-actions'
      - 'ci/cd'
      - 'automated'
