# Improved Dependabot configuration - fewer, smarter updates
version: 2
updates:
  # Consolidate to single root npm config with better grouping and scheduling
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly' # Reduced frequency
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 5 # Reduced from 35+ total
    assignees:
      - '@WolfOfTheNorth'
    reviewers:
      - '@WolfOfTheNorth'
    commit-message:
      prefix: 'chore(deps)'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'automated'

    # Block problematic major updates
    ignore:
      - dependency-name: 'react'
        update-types: ['version-update:semver-major']
      - dependency-name: 'react-dom'
        update-types: ['version-update:semver-major']
      - dependency-name: 'typescript'
        update-types: ['version-update:semver-major']
      - dependency-name: 'eslint'
        update-types: ['version-update:semver-major']
      - dependency-name: '@typescript-eslint/*'
        update-types: ['version-update:semver-major']
      - dependency-name: 'vite'
        update-types: ['version-update:semver-major']
      - dependency-name: 'jest'
        update-types: ['version-update:semver-major']

    # Smart grouping to reduce PR count
    groups:
      # Critical framework updates (careful review needed)
      react-ecosystem:
        patterns:
          - 'react*'
          - '@types/react*'
        update-types:
          - 'minor'
          - 'patch'

      # TypeScript ecosystem (likely to cause conflicts)
      typescript-ecosystem:
        patterns:
          - 'typescript'
          - '@typescript-eslint/*'
          - '@types/*'
        update-types:
          - 'minor'
          - 'patch'

      # Testing tools (can break together)
      testing-ecosystem:
        patterns:
          - 'jest*'
          - '@testing-library/*'
          - 'playwright*'
          - '@playwright/*'
          - 'supertest'
        update-types:
          - 'minor'
          - 'patch'

      # Linting tools (style/config changes)
      linting-ecosystem:
        patterns:
          - 'eslint*'
          - '@eslint/*'
          - 'prettier'
        update-types:
          - 'minor'
          - 'patch'

      # Build tools (can affect entire monorepo)
      build-tools:
        patterns:
          - 'vite*'
          - '@vitejs/*'
          - 'rollup*'
          - 'webpack*'
          - 'concurrently'
        update-types:
          - 'minor'
          - 'patch'

      # Safe utility updates (low risk)
      utilities:
        patterns:
          - 'chalk'
          - 'glob'
          - 'minimist'
          - 'husky'
          - 'lint-staged'
        update-types:
          - 'minor'
          - 'patch'

  # Backend Python - keep separate due to different ecosystem
  - package-ecosystem: 'pip'
    directory: '/apps/backend'
    schedule:
      interval: 'monthly' # Reduced frequency
      day: 'tuesday'
      time: '09:00'
    open-pull-requests-limit: 3
    commit-message:
      prefix: 'chore(backend/deps)'
    labels:
      - 'dependencies'
      - 'backend'
      - 'python'
      - 'automated'
    ignore:
      - dependency-name: 'django'
        update-types: ['version-update:semver-major']

  # Docker - keep monthly for security
  - package-ecosystem: 'docker'
    directory: '/infra/docker'
    schedule:
      interval: 'monthly'
      day: 'monday'
      time: '10:00'
    open-pull-requests-limit: 2
    commit-message:
      prefix: 'chore(docker)'
    labels:
      - 'dependencies'
      - 'docker'
      - 'infrastructure'
      - 'automated'

  # GitHub Actions - quarterly for stability
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
      day: 'monday'
      time: '11:00'
    open-pull-requests-limit: 3
    commit-message:
      prefix: 'chore(ci)'
    labels:
      - 'dependencies'
      - 'github-actions'
      - 'ci/cd'
      - 'automated'
